### ISSUE TITLE
Parse error: syntax error, unexpected T_NAMESPACE, expecting T_STRING

### ISSUE THREAD

**Issue by r-martins** [EcomDev/EcomDev_ProductPageShipping#1]
Parse error: syntax error, unexpected T_NAMESPACE, expecting T_STRING in (...)/app/code/community/EcomDev/ProductPageShipping/Model/Session.php on line 26

**Comment by dfelton** [comment]
The author of this extension seems to no longer maintain it. For those who come here if the issue still exists simply rename the constant on that file. I simply renamed it from NAMESPACE to PRODUCTPAGESHIPPING_NAMESPACE.

**Comment by IvanChepurnyi** [comment]
This extension is out-dated and not supported anymore.
