### ISSUE TITLE
Resulting Array of Shipping Rates 

### ISSUE THREAD

**Issue by ArunaShetty** [EcomDev/EcomDev_ProductPageShipping#12]
On providing the zipcode we are not getting the correct shipping rates. The function estimate() returning  shipping rates using $shippingAddress->getGroupedAllShippingRates() . This code is listing array of shipping rates which is  having mutilpe rates for the same method . please Let me know which rates(price) has to be taken from array.

**Comment by IvanChepurnyi** [comment]
This extension is out-dated and not supported anymore.
