### ISSUE TITLE
Doest calculate correct shipping for configurable product.

### ISSUE THREAD

**Issue by ankitsam** [EcomDev/EcomDev_ProductPageShipping#3]
I am using webshops matrix caluclation for configurable product, shipping cost is calculated based on price.

The "ProductPageShipping" form calculates based on base price of configurable product, not on price of selected simple products.

Hence, returns different shipping cost on product page and shopping cart page.

Thanks for great extension.
(y)

**Comment by IvanChepurnyi** [comment]
This extension is out-dated and not supported anymore.
