### ISSUE TITLE
How can i place form in a custom position?

### ISSUE THREAD

**Issue by fernandoperigolo** [EcomDev/EcomDev_ProductPageShipping#5]
I created a new ```<?php echo $this->getChildHtml('ecomdev_productpageshipping') ?>``` in product view template and i wish to place form here. What i need to do?

**Comment by viniciuscenci** [comment]
<?php echo $this->getLayout()->getBlock('shipping.estimate.form')->toHtml()?>

**Comment by IvanChepurnyi** [comment]
This extension is out-dated and not supported anymore.

**Comment by viniciuscenci** [comment]
I get it. But still works right in the latest version of Magento 1.9.2.1 ;)

2015-09-07 6:36 GMT-03:00 Ivan Chepurnyi <notifications@github.com>:
